run:
  deadline: 300s
  skip-dirs:
    - config
    - hack/licence\-detector
  skip-files:
    - utils/chrono/millis\.test\.go
linters:
  enable-all: true
  disable:
    - funlen # checks function length, not very useful
    - gochecknoglobals
    - gochecknoinits
    # - gocognit # added in 1.20
    - godot # added in 1.25
    - godox # calls out TODOs
    - goerr113
    - gomnd # added in 1.23
    - interfacer
    - lll
    - nestif # added in 1.25
    - nlreturn # just ensures there are newlines before returns, not very useful
    - scopelint
    - testpackage # added in 1.25
    - whitespace # added in 1.19
    - wsl # added in 1.20
linters-settings:
  maligned:
    suggest-new: true
issues:
  exclude-rules:
    - linters:
        - golint
      text: 'name .* stutters'
    - path: (^test/.*\.go|.*_test\.go)
      linters:
        - goconst
        - unparam
    - linters:
        - gosec
      # this was added in https://github.com/securego/gosec/issues/438 but for our use case is more or less entirely false positives
      text: 'G601: Implicit memory aliasing in for loop.'
    - path: pkg/controller/elasticsearch/client/client\.go # this is not a comment indicating the func is deprecated
      text: 'deprecatedComment: the proper format is'
    - linters:
      - noctx
      path: "test/e2e/.*.go" # currently do not care about passing contexts around for e2e test checks
    - linters:
        - dupl
      path: (^test/.*\.go|.*_test\.go) # do not care about duplicate code in tests
