run:
  deadline: 300s
linters:
  enable-all: true
  disable:
    - funlen # checks function length, not very useful
    - gochecknoglobals
    - gochecknoinits
    - gocognit # flags cognitive complexity, TODO review in future
    - godox # calls out TODOs, not very useful
    - goerr113 # calls out dynamic errors, TODO review in future
    - gomnd # detects magic numbers, TODO review in future
    - interfacer # linter is archived
    - lll # checks line length, not very useful
    - nestif # added in 1.25
    - nlreturn # just ensures there are newlines before returns, not very useful
    - scopelint # linter is deprecated for exportloopref
    - testpackage # makes you use a separate test pkg, not useful
    - whitespace # detects leading/trailing whitespace, not very useful
    - wsl # forces extra whitespace, not very useful
linters-settings:
  maligned:
    suggest-new: true
issues:
  exclude-rules:
    - linters:
        - golint
      text: 'name .* stutters'
    - path: (^test/.*\.go|.*_test\.go)
      linters:
        - dupl # do not care about duplicate code in tests
        - goconst # do not care about potential constant refactoring in tests
        - unparam # do not care about unused params in tests
    - linters:
        - gosec
      # this was added in https://github.com/securego/gosec/issues/438 but for our use case is more or less entirely false positives
      text: 'G601: Implicit memory aliasing in for loop.'
    - path: pkg/controller/elasticsearch/client/client\.go # this is not a comment indicating the func itself is deprecated
      text: 'deprecatedComment: the proper format is'
    - linters:
      - noctx
      path: "test/e2e/.*" # currently do not care about passing contexts around for e2e test checks
